# Generated by Django 3.0.5 on 2020-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='bid_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitems',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
