# Generated by Django 3.0.8 on 2020-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0003_auto_20200710_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
