# Generated by Django 3.0.8 on 2020-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_auctionitems_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
