# Generated by Django 3.0.8 on 2020-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0005_auctionitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitems',
            name='number_of_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
