# Generated by Django 3.0.8 on 2020-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0006_auctionitems_number_of_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitems',
            name='number_of_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
