# Generated by Django 3.0.8 on 2020-07-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0007_auto_20200715_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitems',
            name='bid_time',
        ),
    ]
